In [5]:
import torch.nn as nn
import numpy as np
import torch

In [6]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [7]:
from torch.utils.data import TensorDataset

In [8]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [9]:
from torch.utils.data import DataLoader

In [10]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [33]:
for a, b in train_dl:
    print(a)
    print(b)

tensor([[ 68.,  96.,  71.],
        [ 87., 135.,  57.],
        [ 91.,  88.,  64.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.]])
tensor([[104., 118.],
        [118., 134.],
        [ 81., 101.],
        [ 80., 102.],
        [118., 132.]])
tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 92.,  87.,  64.],
        [ 87., 134.,  58.],
        [ 74.,  66.,  43.]])
tensor([[103., 119.],
        [ 22.,  37.],
        [ 82., 100.],
        [119., 133.],
        [ 57.,  69.]])
tensor([[103.,  43.,  36.],
        [ 73.,  67.,  43.],
        [ 73.,  66.,  44.],
        [ 68.,  97.,  70.],
        [101.,  44.,  37.]])
tensor([[ 20.,  38.],
        [ 56.,  70.],
        [ 57.,  69.],
        [102., 120.],
        [ 21.,  38.]])


In [23]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1697,  0.1420, -0.4562],
        [ 0.4988, -0.3405,  0.1738]], requires_grad=True)
Parameter containing:
tensor([-0.3515, -0.3051], requires_grad=True)


In [24]:
preds = model(inputs)
preds

tensor([[ 1.9301, 20.7687],
        [-1.6147, 26.2465],
        [ 6.9744,  7.5472],
        [ 6.1811, 42.3629],
        [-6.9494, 13.5914],
        [ 1.9579, 21.6080],
        [-2.2129, 26.7607],
        [ 6.6879,  8.2198],
        [ 6.1534, 41.5236],
        [-7.5753, 13.2664],
        [ 1.3320, 21.2829],
        [-1.5870, 27.0858],
        [ 7.5726,  7.0330],
        [ 6.8070, 42.6880],
        [-6.9771, 12.7522]], grad_fn=<AddmmBackward0>)

In [25]:
import torch.nn.functional as F
loss_fn = F.mse_loss

In [26]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(6938.4707, grad_fn=<MseLossBackward0>)


In [27]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [36]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    for epoch in range(num_epochs):
        
        for xb,yb in train_dl:

            pred = model(xb)

            loss = loss_fn(pred, yb)
            
            loss.backward()
            
            opt.step()
            
            opt.zero_grad()
        
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [37]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 302.3612
Epoch [20/100], Loss: 305.4959
Epoch [30/100], Loss: 332.0916
Epoch [40/100], Loss: 176.7237
Epoch [50/100], Loss: 100.1480
Epoch [60/100], Loss: 94.6886
Epoch [70/100], Loss: 67.4884
Epoch [80/100], Loss: 53.7508
Epoch [90/100], Loss: 35.2861
Epoch [100/100], Loss: 34.4594


In [38]:
preds = model(inputs)
preds

tensor([[ 58.1366,  71.6198],
        [ 78.2519,  99.4315],
        [124.8768, 133.3103],
        [ 27.5953,  45.0019],
        [ 91.2599, 112.2875],
        [ 56.9322,  70.6914],
        [ 77.3524,  99.2460],
        [124.7957, 133.8103],
        [ 28.7997,  45.9303],
        [ 91.5648, 113.0304],
        [ 57.2371,  71.4342],
        [ 77.0475,  98.5031],
        [125.7763, 133.4958],
        [ 27.2905,  44.2590],
        [ 92.4643, 113.2160]], grad_fn=<AddmmBackward0>)

In [39]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.8169, 68.7704]], grad_fn=<AddmmBackward0>)